# Generated by Django 5.2.8 on 2025-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craftsperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('preposition', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence_label', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('craftspeople', models.ManyToManyField(related_name='buildings', to='core.craftsperson')),
            ],
        ),
    ]
