# Generated by Django 5.2.8 on 2025-11-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsperson',
            name='surname',
            field=models.CharField(
                db_index=True,
                default='Unknown',
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
