# Generated by Django 5.2.8 on 2025-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_craftsperson_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsperson',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
