# Generated by Django 5.2.8 on 2025-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_craftsperson_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsperson',
            name='surname',
        ),
        migrations.AddField(
            model_name='craftsperson',
            name='forename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='craftsperson',
            name='name',
            field=models.CharField(db_index=True, default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
