# Generated by Django 6.0.5 on 2026-05-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='surname',
        ),
    ]
