# Generated by Django 6.0.5 on 2026-05-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_rename_name_person_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='label',
            field=models.CharField(blank=True, help_text='e.g. the Mason, the Elder, the Younger', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='preposition',
            field=models.CharField(blank=True, help_text='e.g. de, von, van, ap, fitz', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sequence_label',
            field=models.CharField(blank=True, help_text='e.g. II, III, Junior', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
