# Generated by Django 6.0.5 on 2026-06-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_options_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('bricklayer', 'Bricklayer'), ('brickmaker', 'Brickmaker'), ('carver', 'Carver'), ('carpenter', 'Carpenter'), ('clerical artist', 'Clerical Artist'), ('engineer', 'Engineer'), ('graver', 'Graver'), ('imager', 'Imager'), ('joiner', 'Joiner'), ('marbler', 'Marbler'), ('mason', 'Mason'), ('sculptor', 'Sculptor'), ('tomb maker', 'Tomb Maker')], help_text='Primary occupation or craft', max_length=50, null=True),
        ),
    ]
