# Generated by Django 6.0.5 on 2026-06-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0001_initial'),
        ('people', '0005_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_of', to='chronology.uncertaindate'),
        ),
        migrations.AddField(
            model_name='person',
            name='death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_of', to='chronology.uncertaindate'),
        ),
        migrations.AddField(
            model_name='person',
            name='floruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floruit_of', to='chronology.uncertaindate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('bricklayer', 'Bricklayer'), ('brickmaker', 'Brickmaker'), ('carver', 'Carver'), ('carpenter', 'Carpenter'), ('clerical artist', 'Clerical Artist'), ('engineer', 'Engineer'), ('graver', 'Graver'), ('imager', 'Imager'), ('joiner', 'Joiner'), ('layman', 'Layman'), ('marbler', 'Marbler'), ('mason', 'Mason'), ('millwright', 'Millwright'), ('monk', 'Monk'), ('priest', 'Priest'), ('sculptor', 'Sculptor'), ('tomb maker', 'Tomb Maker')], help_text='Primary occupation or craft', max_length=50, null=True),
        ),
    ]
