# Generated by Django 6.0.5 on 2026-07-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0002_alter_uncertaindate_options_and_more'),
        ('people', '0006_person_birth_person_death_person_floruit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='floruit',
        ),
        migrations.AddField(
            model_name='person',
            name='floruit_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floruit_end_of', to='chronology.uncertaindate'),
        ),
        migrations.AddField(
            model_name='person',
            name='floruit_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floruit_start_of', to='chronology.uncertaindate'),
        ),
    ]
