# Generated by Django 6.0.5 on 2026-07-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0004_alter_uncertaindate_qualifier'),
        ('people', '0007_remove_person_birth_remove_person_floruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_of', to='chronology.uncertaindate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floruit_end',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floruit_end_of', to='chronology.uncertaindate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floruit_start',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floruit_start_of', to='chronology.uncertaindate'),
        ),
    ]
