# Generated by Django 6.0.5 on 2026-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_alter_person_death_alter_person_floruit_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
    ]
