# Generated by Django 6.0.5 on 2026-05-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_alter_person_options_person_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('people', models.ManyToManyField(blank=True, help_text='People associated with this building', related_name='buildings', to='people.person')),
            ],
        ),
    ]
