# Generated by Django 6.0.5 on 2026-07-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0008_alter_person_death_alter_person_floruit_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ecclesiastical", "Ecclesiastical"),
                            ("domestic", "Domestic"),
                            ("military", "Military"),
                            ("civic", "Civic / Urban"),
                        ],
                        help_text="Broad category of building type",
                        max_length=20,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("abbey", "Abbey"),
                            ("priory", "Priory"),
                            ("friary", "Friary"),
                            ("cathedral", "Cathedral"),
                            ("collegiate_church", "Collegiate Church"),
                            ("parish_church", "Parish Church"),
                            ("manor_house", "Manor House"),
                            ("hall_house", "Hall House"),
                            ("farmstead", "Farmstead"),
                            ("castle", "Castle"),
                            ("tower_house", "Tower House"),
                            ("fortified_manor", "Fortified Manor"),
                            ("guildhall", "Guildhall"),
                            ("market_hall", "Market Hall"),
                            ("gatehouse", "Gatehouse"),
                            ("memorial_cross", "Memorial Cross"),
                        ],
                        help_text="Specific type of building",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bedfordshire", "Bedfordshire"),
                            ("Berkshire", "Berkshire"),
                            ("Buckinghamshire", "Buckinghamshire"),
                            ("Cambridgeshire", "Cambridgeshire"),
                            ("Cheshire", "Cheshire"),
                            ("Cornwall", "Cornwall"),
                            ("Cumberland", "Cumberland"),
                            ("Derbyshire", "Derbyshire"),
                            ("Devon", "Devon"),
                            ("Dorset", "Dorset"),
                            ("Durham", "Durham"),
                            ("Essex", "Essex"),
                            ("Gloucestershire", "Gloucestershire"),
                            ("Hampshire", "Hampshire"),
                            ("Herefordshire", "Herefordshire"),
                            ("Hertfordshire", "Hertfordshire"),
                            ("Huntingdonshire", "Huntingdonshire"),
                            ("Kent", "Kent"),
                            ("Lancashire", "Lancashire"),
                            ("Leicestershire", "Leicestershire"),
                            ("Lincolnshire", "Lincolnshire"),
                            ("Middlesex", "Middlesex"),
                            ("Norfolk", "Norfolk"),
                            ("Northamptonshire", "Northamptonshire"),
                            ("Northumberland", "Northumberland"),
                            ("Nottinghamshire", "Nottinghamshire"),
                            ("Oxfordshire", "Oxfordshire"),
                            ("Rutland", "Rutland"),
                            ("Shropshire", "Shropshire"),
                            ("Somerset", "Somerset"),
                            ("Staffordshire", "Staffordshire"),
                            ("Suffolk", "Suffolk"),
                            ("Surrey", "Surrey"),
                            ("Sussex", "Sussex"),
                            ("Warwickshire", "Warwickshire"),
                            ("Westmorland", "Westmorland"),
                            ("Wiltshire", "Wiltshire"),
                            ("Worcestershire", "Worcestershire"),
                            ("Yorkshire", "Yorkshire"),
                        ],
                        help_text="Historic county in England",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True,
                        help_text="People associated with this building",
                        related_name="buildings",
                        to="people.person",
                    ),
                ),
                (
                    "building_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.buildingtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeoRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_ref",
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic Reference",
                "verbose_name_plural": "Geographic References",
            },
        ),
    ]
