# Generated by Django 6.0.5 on 2026-07-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildingtype",
            name="description",
        ),
        migrations.RemoveField(
            model_name="buildingtype",
            name="name",
        ),
    ]
