# Generated by Django 6.0.5 on 2026-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='county',
            field=models.CharField(blank=True, choices=[('Bedfordshire', 'Bedfordshire'), ('Berkshire', 'Berkshire'), ('Buckinghamshire', 'Buckinghamshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Cheshire', 'Cheshire'), ('Cornwall', 'Cornwall'), ('Cumberland', 'Cumberland'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Hampshire', 'Hampshire'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Huntingdonshire', 'Huntingdonshire'), ('Kent', 'Kent'), ('Lancashire', 'Lancashire'), ('Leicestershire', 'Leicestershire'), ('Lincolnshire', 'Lincolnshire'), ('Middlesex', 'Middlesex'), ('Norfolk', 'Norfolk'), ('Northamptonshire', 'Northamptonshire'), ('Northumberland', 'Northumberland'), ('Nottinghamshire', 'Nottinghamshire'), ('Oxfordshire', 'Oxfordshire'), ('Rutland', 'Rutland'), ('Shropshire', 'Shropshire'), ('Somerset', 'Somerset'), ('Staffordshire', 'Staffordshire'), ('Suffolk', 'Suffolk'), ('Surrey', 'Surrey'), ('Sussex', 'Sussex'), ('Warwickshire', 'Warwickshire'), ('Westmorland', 'Westmorland'), ('Wiltshire', 'Wiltshire'), ('Worcestershire', 'Worcestershire'), ('Yorkshire', 'Yorkshire')], help_text='Historic county in England', max_length=20, null=True),
        ),
    ]
