# Generated by Django 6.0.5 on 2026-07-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0005_uncertaindate_month_uncertaindate_day'),
        ('buildings', '0003_category_element_alter_buildingtype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='construction_end',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_end_of', to='chronology.uncertaindate'),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_start',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_start_of', to='chronology.uncertaindate'),
        ),
    ]