# Generated by Django 6.0.5 on 2026-07-18 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_ref', to='buildings.building')),
            ],
        ),
    ]
