# Generated by Django 6.0.5 on 2026-07-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'chronology',
            '0005_uncertaindate_month_uncertaindate_day',
        ),
        (
            'people',
            '0008_alter_person_death_alter_person_floruit_end_and_more',
        ),
        (
            'buildings',
            '0004_building_construction_start_building_construction_end',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPhase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notes',
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    'building',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='phases',
                        to='buildings.building',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='building_phases',
                        to='people.person',
                    ),
                ),
                (
                    'end',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='building_phase_end_of',
                        to='chronology.uncertaindate',
                    ),
                ),
                (
                    'start',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='building_phase_start_of',
                        to='chronology.uncertaindate',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Building Phase',
                'verbose_name_plural': 'Building Phases',
                'ordering': ['building', 'start', 'id'],
            },
        ),
    ]
