# Generated by Django 6.0.5 on 2026-07-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_georef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='georef',
            options={'verbose_name': 'Geographic Reference', 'verbose_name_plural': 'Geographic References'},
        ),
    ]
