# Generated by Django 6.0.5 on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_buildingphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingphase',
            name='elements',
            field=models.ManyToManyField(
                blank=True,
                related_name='building_phases',
                to='buildings.element',
            ),
        ),
    ]
