# Generated by Django 6.0.5 on 2026-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UncertainDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('qualifier', models.CharField(choices=[('exact', 'Exact'), ('circa', 'Circa'), ('before', 'Before'), ('after', 'After'), ('range', 'Range'), ('floruit', 'Floruit'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('original_label', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
