# Generated by Django 6.0.5 on 2026-06-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uncertaindate',
            options={'verbose_name': 'date', 'verbose_name_plural': 'dates'},
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='original_label',
        ),
    ]
