# Generated by Django 6.0.5 on 2026-07-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0002_alter_uncertaindate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uncertaindate',
            old_name='end_day',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='uncertaindate',
            name='start_year',
        ),
    ]
