# Generated by Django 6.0.5 on 2026-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0003_rename_end_day_uncertaindate_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncertaindate',
            name='qualifier',
            field=models.CharField(choices=[('exact', 'Exact'), ('circa', 'Circa'), ('before', 'Before'), ('after', 'After'), ('range', 'Range'), ('unknown', 'Unknown')], default='exact', max_length=20),
        ),
    ]
