# Generated by Django 6.0.5 on 2026-07-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0004_alter_uncertaindate_qualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncertaindate',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uncertaindate',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]